# Generated by Django 4.2.4 on 2023-08-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_tag_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='image',
            new_name='name',
        ),
    ]
